#!/bin/bash

### BEGIN INIT INFO
# Provides:        ckpl
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start Blueocean node 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib/klibc/bin

. /lib/lsb/init-functions

# Zmienne:
BOCOMPUTE=bocomputex
BO_VERSION="v2.1.2"
BO_REPO="bockpl/${BOCOMPUTE}:${BO_VERSION}"
DEV_NAME=bond0 
BO_NUMBER="$(echo $(ip addr show $DEV_NAME | grep inet | cut -d"/" -f1 | rev | cut -d"." -f1 | rev))"
BO_HOSTNAME="bo$BO_NUMBER"
BO_IP="10.0.0.$BO_NUMBER"
# Do okreslenia cech i wprowadzenia limitu cpu ALL -1cpu:
ILOSC_RDZENI_CPU=$(nproc)
RDZENIE_BOCOMPUTE=$(expr $ILOSC_RDZENI_CPU - 1)
# Do okreslenia  cech i limitow pamieci ALL -4GB:
ILOSC_PAMIECI=$(docker info |grep "Total Memory:" | rev |awk '{print $1}'| rev | cut -d "." -f1)
PAMIEC_BOCOMPUTE=$(expr $ILOSC_PAMIECI - 4)
PAMIEC_BOCOMPUTE_G="$(echo ""$PAMIEC_BOCOMPUTE"G")"
#
SHM_SIZE="$(df -h |grep /dev/shm | awk '{print $2}' | rev |cut -c 2- |rev | xargs -I{} expr {} - 1)g"
# Deklaracja zmiennych mfs sciezek home i opt
BO_HOME="/home"
BO_OPT="/opt"
MFS_CHUNK="/opt"
MFS_TARGET=""
MFS_BASICPATH="/blueocean"
MFS_LOCALPATH="/srv/blueocean"
MFS_HOME="$MFS_LOCALPATH/home"
MFS_OPT="$MFS_LOCALPATH/opt"
MFS_CONFIGS="$MFS_OPT/software/Blueocean/Configs"
# Deklaracja sciezki LDAP
MFS_LDAPCONF="$MFS_CONFIGS/nslcd.conf"
BO_LDAPCONF="/etc/nslcd.conf"
# Deklaracja aliasow
MFS_ALIAS="$MFS_CONFIGS/aliases"
BO_ALIAS="/etc/aliases"
# Deklaracja msmtp
MFS_MSMTP="$MFS_CONFIGS/msmtprc"
BO_MSMTP="/etc/msmtprc"
# Deklaracja sciezki SLURM
MFS_SLURMCONF="$MFS_CONFIGS/slurmconf"
BO_SLURMCONF="/etc/slurm"
# Deklaracja sciezki dbd
MFS_SLURMDBD="$MFS_CONFIGS/slurmdbd"
BO_SLURMDBD="/var/lib/slurmd"
## Deklaracja cephfs
CEPHFS_PATH="/srv/blueocean/cephfs/soft/miniconda3"
BO_CEPHFS_PATH="/opt/miniconda3"
# deklaracja DinD
DinD="-v /var/run/docker.sock:/var/run/docker.sock --privileged"
minusV="${DinD} -v ${MFS_OPT}:${BO_OPT} -v ${MFS_HOME}:${BO_HOME} -v ${MFS_LDAPCONF}:${BO_LDAPCONF} -v ${MFS_SLURMCONF}:${BO_SLURMCONF} -v ${MFS_SLURMDBD}:${BO_SLURMDBD} -v ${CEPHFS_PATH}:${BO_CEPHFS_PATH} -v ${MFS_ALIAS}:${BO_ALIAS} -v ${MFS_MSMTP}:${BO_MSMTP} "
# Deklaracja portów
BO_PORTS="" 
# Deklaracja srodowiska NVIDIA
BO_NVIDIA="" 

# Sprawdzanie czy nod jest czescia klastra Blueocean SWARM
function isSwarmNode(){
	if [ "$(docker info | grep Swarm | rev | cut -d' ' -f1 | rev)" == "active" ] ; then
		return 0
	else
        	return 1
	fi
}

# Pobranie aktualnej konfiguracji swarm:
function getManagerSwarm() {
	SWARMMAN=$(cat $MFS_CONFIGS/swarm_manager.list) 
}

# montowanie mfs
function MFSpathMounter() {
        if [ "$MFS_TARGET" == "" ]; then
                echo "Nieokreslona sciezka dla MFSpathMounter"
        else
                mfsmount -H mfsmaster.dev.p.lodz.pl -S $MFS_BASICPATH/$MFS_TARGET $MFS_LOCALPATH/$MFS_TARGET >& /dev/null
        fi
}

# odmontowanie mfs
function MFSpathUmounter() {
        if [  "$MFS_TARGET" == "" ]; then
                echo "Nieokreslona sciezka dla MFSpathUmounter"
        else
                umount $MFS_LOCALPATH/$MFS_TARGET
        fi
}

# sprawdzenie czy mfs jest zamontowany
function MFSpathChecker() {
        if [  "$MFS_TARGET" == "" ]; then
                echo "Nieokreslona sciezka dla MFSpathChecker"
        else
                if [ "`cat /proc/mounts | grep mfs | cut -d' ' -f2 | grep "$MFS_LOCALPATH/$MFS_TARGET"`" == "" ]; then
                        return 1
                else
                        return 0
                fi
        fi
}


case $1 in
        start)
                # Montowanie MFS
                for i in home opt ; do
                        MFS_TARGET="$i"
                        MFSpathChecker
                        MFS_STATE=$?
                        if [ $MFS_STATE == 1 ]; then
                                # to be mounted
                                echo "$MFS_LOCALPATH/$MFS_TARGET zostanie zamontowane"
                                MFSpathMounter
                        elif [ $MFS_STATE == 0 ]; then
                                # mounted
                                echo "Znaleziono zamontowane $MFS_LOCALPATH/$MFS_TARGET"
                        elif [ $MFS_STATE == 2 ]; then
                                echo "Problem z prawidlowym wyszukaniem $MFS_LOCALPATH/$MFS_TARGET"
                        fi
                        MFS_TARGET=""
                done

		# Sprawdzenie czy nod jest czescia swarma
		isSwarmNode
		Status=$?
		if [[ $Status = 0 ]]; then
				echo "Nod jest czescia klastra Bluecoean SWARM "
			else
				log_daemon_msg "Add node to Blueocan Docker SWARM"
				echo "Nod nie jest czescia klastra Blueocean SWARM, podejmuje probe dolaczenia:"

				# Wybranie dzialajacego managera swarm:
				getManagerSwarm
				for MANAGER in $(echo $SWARMMAN); do
					nmap -p 2377 $MANAGER |grep open > /dev/null
					MANAGER_STATUS=$?
					if [ $MANAGER_STATUS -eq 0 ]; then
						echo "Aktywny Manager Blueceoan SWARM: $MANAGER"
						break 
					fi 
				done

				# Dolaczenie noda do Klastra Blueocean SWARM:
				log_daemon_msg "Add node to Blueocean SWARM klaster"
				docker swarm join --token SWMTKN-1-03i2d2uwietrhya3b5qtryyyurzvxkg08wj2av06zm3q9jqut2-0i8gc7v463lmtpofab2urahx7 $MANAGER:2377
				status=$?
                                log_end_msg $status
		fi

		# Uruchomienie kontenera:
		if ! (docker ps -a|grep -q ${BO_HOSTNAME}); then
				log_daemon_msg "Build  and start ${BO_HOSTNAME} container"
                                docker run -dt --rm --name ${BO_HOSTNAME} -h $BO_HOSTNAME --cpus $RDZENIE_BOCOMPUTE --memory $PAMIEC_BOCOMPUTE_G \
                                --memory-swap $PAMIEC_BOCOMPUTE_G --shm-size=$SHM_SIZE ${minusV} ${BO_NVIDIA} ${BO_PORTS} --net cluster_network --ip $BO_IP ${BO_REPO} 
				status=$?
                		log_end_msg $status
			else
				log_daemon_msg "Start ${BO_HOSTNAME} container"
				docker start ${BO_HOSTNAME}
				status=$?
                		log_end_msg $status
		fi
		;;
	stop)
		log_daemon_msg "Stop ${BO_HOSTNAME} container" 
                docker stop ${BO_HOSTNAME}
                status=$?
                log_end_msg $status
                ## odmontowanie MFS
                #for i in home opt ; do
                #        MFS_TARGET="$i"
                #        MFSpathUmounter
                #        MFS_TARGET=""
                #done
		;;
	restart|force-reload)
                $0 stop && sleep 2 && $0 start
                ;;
	 *)
                echo "Usage: $0 {start|stop|restart}"
                exit 2
                ;;
esac

